#include "config.h"

#include "game_str.h"

/* -------------------------------------------------------------------------- */

const char *game_str_tbl_ship_names[RACE_NUM * SHIP_NAME_NUM] = {
    "FIGHTER", "GUNBOAT", "COURIER", "FlIT",
    "FRIGATE", "DESTROYER", "CORVETTE", "A",
    "CRUISER", "ESCORT", "WARSHIP", "BATTLER",
    "DREADNOUGHT", "BATTLESHIP", "DREADSTAR", "KILLSHIP",

    "WOLVERINE", "GRIFFIN", "FERRET", "A",
    "LYNX", "CHEETAH", "BOBCAT", "B",
    "PANTHER", "LEOPARD", "WARCAT", "C",
    "SABRETOOTH", "PUMA", "TIGER", "SMASHER",

    "PIRANHA", "STINGRAY", "MINNOW", "D",
    "MANTA", "BARRACUDA", "MOREY", "E",
    "SHARK", "MAKO", "WHALE", "F",
    "KRAKEN", "MONITOR", "POLARIS", "AGENT",

    "GOBLIN", "CYCLOPS", "DAEMON", "G",
    "BANSHEE", "SPECTRE", "SPIRIT", "H",
    "JUGGERNAUT", "VALKYRIE", "HYDRA", "I"
    "TITAN", "COLOSSUS", "DRAGON", "FIRESHIP",

    "STARFIGHTER", "COMET", "SEEKER", "J"
    "STAR WING", "STAR BLAZER", "STAR STREAK", "STAR JET",
    "STAR BLADE", "DARK STAR", "CORAONA", "ENTREPRISE",
    "SUN FIRE", "STAR FURY", "NOVA", "SUPER",

    "FOXBAT", "SPARROWHAWK", "PELICAN", "K",
    "FALCON", "SKY HAWK", "SPACE GULL", "L",
    "WARBIRD", "WARHAWK", "WAREAGLE", "WARFIGHTER",
    "CONDOR", "DREADWING", "SKY MASTER", "BLEEDER",

    "SABRE", "CUTLASS", "DAGGER", "STILLETTO",
    "LANCER", "PEGASUS", "HORSEMAN", "M",
    "RANGER", "KNIGHT", "AVENGER", "N",
    "DRAGOON", "PALADIN", "EXCALIBER", "SABER",

    "PAW", "PANDA", "PATROL", "O",
    "HUNTER", "GLADIATOR", "SENTINEL", "P",
    "CLAW", "TOOTH", "WARBEAR", "TALON",
    "GRIZZLY", "PUNISHER", "RHINO", "IMPERATOR",

    "MARAUDER", "HYPERION", "DRACHMA", "Q",
    "INTRUDER", "PENETRATOR", "TORMENTER", "R",
    "AJAX", "TORNADO", "NEXUS", "S",
    "NEMESIS", "DEVASTATOR", "ANNIHILATOR", "KILLER",

    "SPIDER", "BUMBLEBEE", "NEEDLE", "THREAD",
    "HORNET", "SCORPION", "VENOM", "SNAKE",
    "TARANTULA", "VIPER", "COBRA", "THINGY",
    "KING COBRA", "BLACK WIDOW", "DEATH WYN", "GASHER",
};
